package com.bookstore.BookStore.Project.model;
// Generated Nov 22, 2019 2:02:17 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonIgnoreType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", schema = "public")
public class Book implements java.io.Serializable {

	private long id;
	private Author author;
	private Category category;
	private Publisher publisher;
	private String bookDescription;
	private Double bookPrice;
	private Date releaseDate;
	private String bookTitle;

	public Book() {
	}

	public Book(long id) {
		this.id = id;
	}

	public Book(long id, Author author, Category category, Publisher publisher, String bookDescription,
			Double bookPrice, Date releaseDate, String bookTitle) {
		this.id = id;
		this.author = author;
		this.category = category;
		this.publisher = publisher;
		this.bookDescription = bookDescription;
		this.bookPrice = bookPrice;
		this.releaseDate = releaseDate;
		this.bookTitle = bookTitle;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	@ManyToOne
	@JoinColumn(name = "author_id")
	public Author getAuthor() {
		return this.author;
	}
	public void setAuthor(Author author) {
		this.author = author;
	}

	
	@ManyToOne 
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}
	public void setCategory(Category category) {
		this.category = category;
	}

	
	@ManyToOne
	@JoinColumn(name = "publisher_id")
	public Publisher getPublisher() {
		return this.publisher;
	}
	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@Column(name = "book_description")
	public String getBookDescription() {
		return this.bookDescription;
	}

	public void setBookDescription(String bookDescription) {
		this.bookDescription = bookDescription;
	}

	@Column(name = "book_price", precision = 17, scale = 17)
	public Double getBookPrice() {
		return this.bookPrice;
	}

	public void setBookPrice(Double bookPrice) {
		this.bookPrice = bookPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 29)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "book_title")
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

}
