package com.bookstore.BookStore.Project.model;
// Generated Nov 22, 2019 2:02:17 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", schema = "public")
public class Grade implements java.io.Serializable {

	private long id;
	private Double bookBaseProduction;
	private String bookQuality;
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Grade() {
	}

	public Grade(long id) {
		this.id = id;
	}

	public Grade(long id, Double bookBaseProduction, String bookQuality, Set<Publisher> publishers) {
		this.id = id;
		this.bookBaseProduction = bookBaseProduction;
		this.bookQuality = bookQuality;
		this.publishers = publishers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "book_base_production")
	public Double getBookBaseProduction() {
		return this.bookBaseProduction;
	}

	public void setBookBaseProduction(Double bookBaseProduction) {
		this.bookBaseProduction = bookBaseProduction;
	}

	@Column(name = "book_quality")
	public String getBookQuality() {
		return this.bookQuality;
	}

	public void setBookQuality(String bookQuality) {
		this.bookQuality = bookQuality;
	}

	@JsonIgnore
	@OneToMany(mappedBy = "grade")
	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
