package com.bookstore.BookStore.Project.model;
// Generated Nov 22, 2019 2:02:17 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Publisher generated by hbm2java
 */
@Entity
@Table(name = "publisher", schema = "public")
public class Publisher implements java.io.Serializable {

	private long id;
	private Grade grade;
	private String countryName;
	private String publisherName;
	private Set<Book> books = new HashSet<Book>(0);

	public Publisher() {
	}

	public Publisher(long id) {
		this.id = id;
	}

	public Publisher(long id, Grade grade, String countryName, String publisherName, Set<Book> books) {
		this.id = id;
		this.grade = grade;
		this.countryName = countryName;
		this.publisherName = publisherName;
		this.books = books;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "grade_id")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@Column(name = "country_name")
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "publisher_name")
	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	@JsonIgnore
	@OneToMany(mappedBy = "publisher")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
